.zuul.yaml
Signed-off-by: Christoph Görn <goern@b4mad.net>
=> added a release pipeline job to push to pypi

Pipfile, Pipfile.lock
=> Remove prereleases

Pipfile, Pipfile.lock, thoth/messaging/unresolved_package.py
=> Add unresolved package message

README.rst, thoth/messaging/__init__.py, thoth/messaging/message_factory.py
Neat li'l function for creating custom messages.  This is useful for testing and for people outside our organization who want to use the messaging module without adding to our repository or for testing before we add new messages to the repo.
=> Message factory

thoth/messaging/unresolved_package.py
=> Use solver and adjust typing

thoth/messaging/unresolved_package.py
It requires new release of thoth-messaging
=> Adjust message specs

cli.py, thoth/messaging/__init__.py, thoth/messaging/cli.py, thoth/messaging/message_base.py, thoth/messaging/message_factory.py
```
$ faust -A cli messaging --topic-name "test" --create-if-not-exist -m '{"word": {"type": "str", "value": "test_val"}}' 
```
=> Add cli for sending a single message to a topic

thoth/messaging/advise_justification.py
=> Add paramter to AdviseJustificaitonMessage

thoth/messaging/solved_package.py
Related-To: https://github.com/thoth-station/adviser/issues/984
Related-To: https://github.com/thoth-station/solver/issues/579
Introduce SolvedPackageMessage to be used in solver workflow
=> Add solved message

thoth/messaging/__init__.py
=> Add missing import

README.rst
=> Adjust README

.github/PULL_REQUEST_TEMPLATE.md
Fixes: https://github.com/thoth-station/messaging/issues/176
=> Add missing PR template

requirements-test.txt, tests/placeholder_test.py
Issues caused by pytest during build do to dependency conflicts
=> remove coala-bears from requirements-test.txt

cli.py
https://github.com/thoth-station/thoth-application/issues/214
=> extra set of parenthesis removed

thoth/messaging/__init__.py, thoth/messaging/unrevsolved_package.py
Related to https://github.com/thoth-station/graph-refresh-job/issues/433
Added unrevsolved class to support messages.
=> Add unrevsolved class

README.rst, docker-compose.yaml
add documentation for developing producers and consumers. Please comment if you believe there is info missing.
=> add dev documentation for thoth-messaging

cli.py
Fixes: https://github.com/thoth-station/messaging/issues/220
Correct bug
=> Correct typo in import

thoth/messaging/advise_justification.py, thoth/messaging/adviser_re_run.py, thoth/messaging/hash_mismatch.py, thoth/messaging/missing_version.py, thoth/messaging/package_releases.py, thoth/messaging/solved_package.py, thoth/messaging/unresolved_package.py, thoth/messaging/unrevsolved_package.py
Correct doc string for messa contents
=> Adjust docstrings

README.rst
=> Adjust links in README

thoth/messaging/__init__.py, thoth/messaging/si_unanalyzed_package.py
Added message topic
related - https://github.com/thoth-station/graph-refresh-job/issues/433
=> Added un analyzed topic

thoth/messaging/__init__.py, thoth/messaging/package_releases.py
Rename to `PackageReleasedMessage`
=> rename to PackageReleasedMessage

cli.py
- Adjust logic for messages in CLI
- Reduce loop check time
- Add more logs to understand what happens
=> Adjust logic and improve logging

thoth/messaging/message_base.py
=> Remove key_type

cli.py
fix logging to use thoth logging
=> move init_logging

thoth/messaging/message_base.py
https://github.com/thoth-station/messaging/issues/225
By default faust stores all data in memory which has two issues:
1. It incurs extra memory overhead
2. There is no way to persist a consumers state if it goes down
By using Faust's rocksDB implementation on the backend, which they recommend for production environments, we can use a PVC to persist consumers' states (specifically thoth-investigator)
I added an optional environment variable which indicates the name of the folder that should be used for the rocksDB, if it is set, then we will use rocksDB to store Faust's state
=> pass directory to store rocksDB

thoth/messaging/inspection_complete.py
https://github.com/thoth-station/thoth-application/issues/398
=> add message for completed inspections

thoth/messaging/message_factory.py, thoth/messaging/update_is_downloadable_ppv.py
https://github.com/thoth-station/thoth-application/issues/507
This message directly corresponds with an update of a row of the python package version table which will be handled by investigator.
Add new message, included `value` so that the operation is reversible if necessary
=> add new message to update flag

thoth/messaging/is_package_si_analyzable.py
Related-To: https://github.com/thoth-station/thoth-application/issues/507
=> Change message

thoth/messaging/update_provides_src_distro.py
https://github.com/thoth-station/thoth-application/issues/507
… Explain your changes.
=> change name of message

thoth/messaging/__init__.py
=> Add missing import in init

thoth/messaging/__init__.py, thoth/messaging/advise_justification.py
=> Add adviser version parameter

thoth/messaging/advise_justification.py, thoth/messaging/adviser_re_run.py, thoth/messaging/adviser_trigger.py, thoth/messaging/hash_mismatch.py, thoth/messaging/inspection_complete.py, thoth/messaging/kebechet_trigger.py, thoth/messaging/message_base.py, thoth/messaging/message_factory.py, thoth/messaging/missing_package.py, thoth/messaging/missing_version.py, thoth/messaging/package_extract_trigger.py, thoth/messaging/package_releases.py, thoth/messaging/provenance_checker_trigger.py, thoth/messaging/qebhwt_trigger.py, thoth/messaging/si_unanalyzed_package.py, thoth/messaging/solved_package.py, thoth/messaging/unresolved_package.py, thoth/messaging/unrevsolved_package.py, thoth/messaging/update_provides_src_distro.py
Add ability for SASL auth
SASL authentication for IBM kafka cluster
=> add option for SASL auth

thoth/messaging/__init__.py, thoth/messaging/advise_justification.py, thoth/messaging/adviser_re_run.py, thoth/messaging/adviser_trigger.py, thoth/messaging/hash_mismatch.py, thoth/messaging/inspection_complete.py, thoth/messaging/kebechet_trigger.py, thoth/messaging/message_base.py, thoth/messaging/missing_package.py, thoth/messaging/missing_version.py, thoth/messaging/package_extract_trigger.py, thoth/messaging/package_releases.py, thoth/messaging/provenance_checker_trigger.py, thoth/messaging/qebhwt_trigger.py, thoth/messaging/si_unanalyzed_package.py, thoth/messaging/solved_package.py, thoth/messaging/unresolved_package.py, thoth/messaging/unrevsolved_package.py, thoth/messaging/update_provides_src_distro.py
https://github.com/thoth-station/messaging/issues/287
This will cause all messages whose topic is determined by version to be lost when investigator updates to the newest version of messaging
Simply add version to message contents. We don't expect this to be set by the user/producer so it is given a default value representing the current iteration
=> add version to message contents

thoth/messaging/__init__.py, thoth/messaging/cve_provided.py
https://github.com/thoth-station/cve-update-job/issues/373
=> add CVEProvidedMessage

.env.template, README.rst, app.sh, requirements.txt, thoth/messaging/message_factory.py
Also, the readme still has bits of Faust and the app.sh has `faust -A main`
=> Updated requirements to use confluent instead of faust

thoth/messaging/__init__.py, thoth/messaging/build_analysis_trigger.py
Related: https://github.com/thoth-station/investigator/pull/393
Related: https://github.com/thoth-station/user-api/pull/1171
Related: https://github.com/thoth-station/common/pull/1073
=> Add build analysis trigger message

thoth/messaging/build_analysis_trigger.py
Let's have the message extended so that it can cover additional metadata.
=> Extend build analysis message

thoth/messaging/__init__.py
bugfix, message not being acknowledged in investigator
=> inspection_complete missing from __init__.py

thoth/messaging/admin_client.py
This function allows a user to check connection to Kafka.  There is no direct way to do this so the easiest thing to do is create a query which simply asks for info about current topics. If this does not complete in the given amount of time then `False` otherwise `True`
=> add function for connection health

thoth/messaging/unresolved_package.py
Related-To: https://github.com/thoth-station/investigator/issues/439
… Explain your changes.
=> Add v1 to message

thoth/messaging/kebechet_run_url.py
https://github.com/thoth-station/kebechet/issues/584
To make informative PRs and issues in Kebechet we need more context.
=> add more metadata and use attr factory

thoth/messaging/package_extract_trigger.py
Related: https://github.com/thoth-station/thoth-application/issues/946
=> Add flag to optionally sync results of package-extract

thoth/messaging/adviser_re_run.py, thoth/messaging/adviser_trigger.py, thoth/messaging/provenance_checker_trigger.py
=> Remove data fields from adviser message

.aicoe-ci.yaml, .prow.yaml
=> add .prow.yaml

thoth/messaging/adviser_trigger.py, thoth/messaging/provenance_checker_trigger.py
https://github.com/thoth-station/investigator/pull/468
https://github.com/thoth-station/thamos/pull/753
https://github.com/thoth-station/kebechet/pull/699
=> add kebechet meta

.thoth.yaml
=> Add Kevin to maintainers

thoth/messaging/kebechet_trigger.py
=> missing config for typing.Any

thoth/messaging/advise_justification.py, thoth/messaging/adviser_trigger.py, thoth/messaging/build_analysis_trigger.py, thoth/messaging/cve_provided.py, thoth/messaging/hash_mismatch.py, thoth/messaging/inspection_complete.py, thoth/messaging/kebechet_run_url.py, thoth/messaging/kebechet_trigger.py, thoth/messaging/message_base.py, thoth/messaging/missing_package.py, thoth/messaging/missing_version.py, thoth/messaging/package_extract_trigger.py, thoth/messaging/package_releases.py, thoth/messaging/provenance_checker_trigger.py, thoth/messaging/qebhwt_trigger.py, thoth/messaging/si_unanalyzed_package.py, thoth/messaging/solved_package.py, thoth/messaging/unresolved_package.py, thoth/messaging/unrevsolved_package.py, thoth/messaging/update_provides_src_distro.py
Closes: https://github.com/thoth-station/messaging/issues/350
=> use Strict types provided by pydantic

README.rst
Readme restructured text code-block fix
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
Fixes: #407 
- [x ] No
the  pypi upload fail due to this change, this would fix it.
we have already uploaded the current version , so no new module release is required.
=> Readme restructured text code-block fix

cli.py
=> flush all pending messages

thoth/messaging/config.py
=> add config for ssl keystore and password

thoth/messaging/adviser_trigger.py, thoth/messaging/provenance_checker_trigger.py
=> fix issue1445 on user-api

thoth/messaging/adviser_trigger.py
Related-To: https://github.com/thoth-station/user-api/issues/1454
=> Remove parameters from adviser trigger message

thoth/messaging/__init__.py, thoth/messaging/thoth_repo_init.py
This will be consumed to schedule thoth-repo-init workflow
=> add new message for triggering thoth-repo-init
